# Generated by Django 5.2.17 on 2026-09-28 21:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAccesoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=150)),
                ('proveedor', models.CharField(max_length=32)),
                ('uid_proveedor', models.CharField(max_length=255)),
                ('nombres', models.CharField(blank=True, max_length=60)),
                ('apellidos', models.CharField(blank=True, max_length=60)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('rol_codigo', models.CharField(blank=True, max_length=32)),
                ('acepto_politicas_en', models.DateTimeField(blank=True, null=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('vence_en', models.DateTimeField()),
                ('utilizado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_sociales_barrio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
