# Generated by Django 5.2.17 on 2026-09-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0002_solicitudaccesosocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='acepto_datos_personales_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
