# Generated by Django 5.2.17 on 2026-09-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0003_perfilusuario_acepto_datos_personales_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='alto_contraste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='canal_preferido',
            field=models.CharField(default='PLATAFORMA', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='contacto_alternativo',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='informacion_adicional',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='recibir_notificaciones',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sector_aproximado',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='estado_aprobacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=12),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
