# Generated by Django 5.2.17 on 2026-09-29 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0004_perfilusuario_alto_contraste_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatares/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='compartir_ubicacion_atencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='disponibilidad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='distancia_maxima_km',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='idioma',
            field=models.CharField(default='es', max_length=8),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='lectura_idioma',
            field=models.CharField(default='es', max_length=8),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='lectura_simplificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='modo_silencioso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='notificaciones_desde',
            field=models.TimeField(default='07:00'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='notificaciones_hasta',
            field=models.TimeField(default='21:00'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ocultar_datos_personales',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ocultar_informacion_adicional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='permitir_contacto_coordinacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='permitir_contacto_usuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='permitir_ubicacion_aproximada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='recibir_mensajes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='recibir_recordatorios',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='recibir_resumen_semanal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='reducir_animaciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='subrayar_enlaces',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tamano_texto',
            field=models.CharField(default='mediano', max_length=12),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='zona_horaria',
            field=models.CharField(default='America/Guayaquil', max_length=40),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='observacion_revision',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_revisados_barrio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SolicitudCorreccionPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta')], default='PENDIENTE', max_length=12)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
