# Generated by Django 5.2.17 on 2026-09-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0005_perfilusuario_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionAval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=240)),
                ('url', models.URLField(max_length=300)),
                ('imagen', models.ImageField(upload_to='instituciones/%Y/%m/')),
                ('activa', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institución que nos avala',
                'verbose_name_plural': 'Instituciones que nos avalan',
                'ordering': ('orden', 'nombre', 'pk'),
            },
        ),
    ]
