# Generated by Django 5.2.17 on 2026-09-30 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0006_institucionaval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('institucion', models.CharField(blank=True, max_length=120)),
                ('mensaje', models.TextField(max_length=3000)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('RESPONDIDO', 'Respondido'), ('CERRADO', 'Cerrado')], db_index=True, default='PENDIENTE', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acuse_enviado_en', models.DateTimeField(blank=True, null=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.TextField(blank=True, max_length=2000)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_revisados_barrio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caso de contacto',
                'verbose_name_plural': 'Casos de contacto',
                'ordering': ('-creado_en',),
            },
        ),
    ]
