# Generated by Django 5.2.17 on 2026-09-30 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0007_casocontacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casocontacto',
            name='estado_notificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casocontacto',
            name='notificacion_estado_pendiente',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ActuacionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREACION', 'Creación'), ('REVISION', 'Revisión'), ('REINTENTO', 'Reintento de notificación')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=15)),
                ('estado_nuevo', models.CharField(max_length=15)),
                ('nota', models.TextField(blank=True, max_length=2000)),
                ('resultado_correo', models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='NO_APLICA', max_length=10)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuaciones_contacto', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones', to='BS.casocontacto')),
            ],
            options={
                'verbose_name': 'Actuación de contacto',
                'verbose_name_plural': 'Actuaciones de contacto',
                'ordering': ('fecha', 'pk'),
            },
        ),
    ]
