# Generated by Django 5.2.17 on 2026-09-30 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0008_casocontacto_estado_notificado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='casocontacto',
            name='nota_revision',
            field=models.TextField(blank=True, help_text='Se enviará por correo al remitente al guardar un cambio de estado o de nota.', max_length=2000, verbose_name='Nota para el remitente'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='acepto_politicas_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActuacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('detalle', models.CharField(blank=True, max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_usuarios_barrio', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones_administrativas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actuación sobre usuario',
                'verbose_name_plural': 'Actuaciones sobre usuarios',
                'ordering': ('-fecha', '-pk'),
            },
        ),
    ]
