# Generated by Django 5.2.17 on 2026-09-30 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0009_alter_casocontacto_nota_revision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=24)),
                ('antes', models.JSONField(blank=True, default=dict)),
                ('despues', models.JSONField(blank=True, default=dict)),
                ('motivo', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_roles_barrio', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_configuracion', to='BS.rol')),
            ],
            options={
                'verbose_name': 'Cambio de rol',
                'verbose_name_plural': 'Cambios de roles',
                'ordering': ('-fecha', '-pk'),
            },
        ),
    ]
