# Generated by Django 5.2.17 on 2026-09-30 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0010_cambiorol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('activo', models.BooleanField(default=False)),
                ('visible_formularios', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo del sistema',
                'verbose_name_plural': 'Catálogos del sistema',
                'ordering': ('nombre', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CambioCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=24)),
                ('detalle', models.CharField(max_length=500)),
                ('antes', models.JSONField(default=dict)),
                ('despues', models.JSONField(default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_publicacion', to='BS.catalogosistema')),
            ],
            options={
                'verbose_name': 'Cambio de catálogo',
                'verbose_name_plural': 'Cambios de catálogos',
                'ordering': ('-fecha', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='BorradorCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(default=dict)),
                ('version_base', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borradores_catalogo', to=settings.AUTH_USER_MODEL)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borradores', to='BS.catalogosistema')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('catalogo', 'actor'), name='bs_borrador_catalogo_actor_unico')],
            },
        ),
        migrations.CreateModel(
            name='ValorCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('disponible_nuevas', models.BooleanField(default=True)),
                ('requiere_ubicacion', models.BooleanField(default=False)),
                ('requiere_validacion', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='BS.catalogosistema')),
            ],
            options={
                'verbose_name': 'Valor de catálogo',
                'verbose_name_plural': 'Valores de catálogo',
                'ordering': ('orden', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('catalogo', 'codigo'), name='bs_catalogo_codigo_unico')],
            },
        ),
    ]
