# Generated by Django 5.2.17 on 2026-09-30 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0011_catalogosistema_cambiocatalogo_borradorcatalogo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='latitud_ubicacion',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='longitud_ubicacion',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ubicacion_actualizada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SolicitudAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(choices=[('PROPIA', 'Para mí'), ('ADULTO_CUIDADO', 'Para un adulto mayor a mi cuidado')], max_length=18)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha_requerida', models.DateField()),
                ('sector_referencia', models.CharField(max_length=160)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('consentimiento_ubicacion_en', models.DateTimeField(blank=True, null=True)),
                ('persona_contacto', models.CharField(max_length=120)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('disponibilidad', models.CharField(max_length=25)),
                ('observaciones', models.TextField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('OBSERVADA', 'Observada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], db_index=True, default='BORRADOR', max_length=12)),
                ('acepto_tratamiento_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('confirmacion_enviada_en', models.DateTimeField(blank=True, null=True)),
                ('confirmacion_pendiente', models.BooleanField(default=False)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.CharField(blank=True, max_length=300)),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_prioridad', to='BS.valorcatalogo')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas_barrio', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_asistencia_barrio', to=settings.AUTH_USER_MODEL)),
                ('tipo_ayuda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_tipo_ayuda', to='BS.valorcatalogo')),
            ],
            options={
                'verbose_name': 'Solicitud de asistencia',
                'verbose_name_plural': 'Solicitudes de asistencia',
                'ordering': ('-creado_en', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ActuacionSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=32)),
                ('descripcion', models.CharField(max_length=350)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuaciones_solicitud_barrio', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones', to='BS.solicitudasistencia')),
            ],
            options={
                'verbose_name': 'Actuación de solicitud',
                'verbose_name_plural': 'Actuaciones de solicitudes',
                'ordering': ('-fecha', '-pk'),
            },
        ),
    ]
