# Generated by Django 5.2.17 on 2026-09-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0012_perfilusuario_latitud_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudasistencia',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
