# Generated by Django 5.2.17 on 2026-09-30 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0013_solicitudasistencia_correo_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Pendiente de revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('RETIRADA', 'Retirada')], db_index=True, default='BORRADOR', max_length=10)),
                ('fecha_disponible', models.DateField(blank=True, null=True)),
                ('hora_desde', models.TimeField(blank=True, null=True)),
                ('hora_hasta', models.TimeField(blank=True, null=True)),
                ('tiene_transporte', models.BooleanField(default=False)),
                ('mensaje', models.CharField(blank=True, max_length=400)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('acepto_revision_en', models.DateTimeField(blank=True, null=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postulaciones', to='BS.solicitudasistencia')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postulaciones_voluntariado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postulación de voluntario',
                'verbose_name_plural': 'Postulaciones de voluntarios',
                'ordering': ('-actualizado_en',),
                'constraints': [models.UniqueConstraint(fields=('solicitud', 'voluntario'), name='bs_postulacion_unica')],
            },
        ),
    ]
