# Generated by Django 5.2.17 on 2026-09-30 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0014_postulacionvoluntario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacionvoluntario',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Pendiente de revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('RETIRADA', 'Retirada'), ('NO_SELECCIONADA', 'No seleccionada')], db_index=True, default='BORRADOR', max_length=16),
        ),
        migrations.CreateModel(
            name='AsignacionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_ATENCION', 'En atención'), ('CIERRE_PENDIENTE', 'Cierre por revisar'), ('COMPLETADA', 'Completada')], db_index=True, default='ASIGNADA', max_length=20)),
                ('fecha_atencion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('instrucciones_voluntario', models.CharField(max_length=400)),
                ('instrucciones_solicitante', models.CharField(max_length=400)),
                ('nota_interna', models.CharField(blank=True, max_length=400)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cierre_en', models.DateTimeField(blank=True, null=True)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_coordinadas', to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion', to='BS.postulacionvoluntario')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion', to='BS.solicitudasistencia')),
            ],
            options={
                'verbose_name': 'Asignación de asistencia',
                'verbose_name_plural': 'Asignaciones de asistencia',
                'ordering': ('-creada_en',),
            },
        ),
    ]
